### ISSUE TITLE
Sourcemaps reference non-existing ts files

### ISSUE THREAD

**Issue by sagilevi** [jsdevtom/take-until-destroy#4]
In the dist folder, the sourcemap files reference non-existing ts files.
For example, file: take-until-destroy.js.map
Contains: "sources":["../src/take-until-destroy.ts"]

this file (and the whole src folder) does not exist in dist, causing warnings.

**Comment by jsdevtom** [comment]
Hi Sagilevi, 

Thank you for your contributions! Can you specify which warnings please?

**Comment by sagilevi** [comment]
Hello,

Thanks for the reply.
I would like to use the latest fixes, please release the latest version(s) to the NPM.

Attached the warnings in this issue:

WARNING in ./node_modules/take-until-destroy/dist/error-messages.js
(Emitted value instead of an instance of Error) Cannot find source file '../src/error-messages.ts': Error: Can't resolve '../src/error-messages.ts' in '[PATH]\node_modules\take-until-destroy\dist'
NonErrorEmittedError: (Emitted value instead of an instance of Error) Cannot find source file '../src/error-messages.ts': Error: Can't resolve '../src/error-messages.ts' in '[PATH]\node_modules\take-until-destroy\dist'

WARNING in ./node_modules/take-until-destroy/dist/take-until-destroy.js
(Emitted value instead of an instance of Error) Cannot find source file '../src/take-until-destroy.ts': Error: Can't resolve '../src/take-until-destroy.ts' in '[PATH]\node_modules\take-until-destroy\dist'
NonErrorEmittedError: (Emitted value instead of an instance of Error) Cannot find source file '../src/take-until-destroy.ts': Error: Can't resolve '../src/take-until-destroy.ts' in
 '[PATH]\node_modules\take-until-destroy\dist'

**Comment by jsdevtom** [comment]
Oops. Forgot to publish. My bad. I have pushed it to npm now. Have the errors gone? I cannot reproduce them in my project.

**Comment by sagilevi** [comment]
It seems that the warnings still exist. It's because there is a reference to non-existent files.
